### ISSUE TITLE
Telescope egrepify don't highlight on preview

### ISSUE THREAD

**Issue by otavioschwanck** [fdschmidt93/telescope-egrepify.nvim#38] opened 2024-03-01 13:01 UTC
### Description

egrepify don't highlight on the item on previewer windows.

### Neovim version

```markdown
latest stable. (0.9.4)
```

### Operating system and version

mac

### Steps to reproduce

Run egrepify with preview

### Expected behavior

Highlight selection like Telescope live_grep

![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/95c84b93-9cf6-4791-88f0-9abefdece76e)

### Actual behavior

Don't highlight on preview.

![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/6fcbc53f-1981-402a-850b-921615cf14b8)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local lazypath = package_root .. "/lazy/lazy.nvim"
local pluginpath = package_root .. "/plugins/"
if not vim.loop.fs_stat(lazypath) then
  print "Installing 'folke/lazy.nvim'..."
  vim.fn.system { "git", "clone", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "fdschmidt93/telescope-egrepify.nvim",
    keys = {
      { "<space>rg", "<CMD>Telescope egrepify<CR>", mode = { "n", "i", "v" } },
    },
  },
  {
    "nvim-telescope/telescope.nvim",
    dependencies = "nvim-lua/plenary.nvim",
    config = function()
      require("telescope").setup {}
      require("telescope").load_extension "egrepify"
    end,
  },
}, { root = pluginpath })
```

**Comment by fdschmidt93** [comment] 2024-03-01 13:25
Screenshot is obviously not from minimal repro. This is more than the third time I am telling you this. I will ignore future bug reports of yours without comments on your next offense.

Back to the issue at hand, I cannot reproduce with appimage from: https://github.com/neovim/neovim/releases/tag/v0.9.5
and 

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local lazypath = package_root .. "/lazy/lazy.nvim"
local pluginpath = package_root .. "/plugins/"
if not vim.loop.fs_stat(lazypath) then
  print "Installing 'folke/lazy.nvim'..."
  vim.fn.system { "git", "clone", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "fdschmidt93/telescope-egrepify.nvim",
    keys = {
      { "<space>rg", "<CMD>Telescope egrepify<CR>", mode = { "n", "i", "v" } },
    },
  },
  {
    "nvim-telescope/telescope.nvim",
    dependencies = "nvim-lua/plenary.nvim",
    config = function()
      require("telescope").setup {}
      require("telescope").load_extension "egrepify"
    end,
  },
}, { root = pluginpath })
```

Closing.

**Closed by fdschmidt93** 2024-03-01 13:25 UTC
Labels: bug
